### ISSUE TITLE
Operation Mode and Firmware Version can't be parsed

### ISSUE THREAD

**Issue by manyos-robert** [manyos-robert/esphome-marax#6]
Further investigation of sscanf and strings needed. Propably caused because %c adds no termination. This causes an crash when data is sent to HA.

**Comment by surealdb** [comment]
I found a fix and implemented it in my fork of your project. Just in case you are interested
kind regards
Matthias

**Comment by manyos-robert** [comment]
Sure! Can you send a pull request? I’ll add it. Thanks. Robert.

**Comment by surealdb** [comment]
I would, but I made the fork as I wanted to change many things, so the fix is not isolated enough for a PR.
I you like you may have a look at https://github.com/surealdb/esphome-marax/blob/14fb4fa817e9e6e7a85d00af45588081779afdda/coffee.yaml#L182, and its usage in https://github.com/surealdb/esphome-marax/blob/14fb4fa817e9e6e7a85d00af45588081779afdda/coffee.yaml#L197 
and https://github.com/surealdb/esphome-marax/blob/14fb4fa817e9e6e7a85d00af45588081779afdda/coffee.yaml#L204

**Comment by manyos-robert** [comment]
Understand! I'll try to add it. Thanks a lot!

**Comment by manyos-robert** [comment]
Works great. Thanks Matthias @surealdb
